filtermetmasker_gemgrijs: verbeterdfiltermetmasker_gemgrijs.c
	cc filtermetmasker_gemgrijs.c -Wall -o filtermetmasker_gemgrijs -ggdb -I/usr/X11R6/include\
-I/usr/local/include -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXext -ljpeg -lpng -ltiff  -lz -lgif -lm -lImlib
