verbeterdfiltermetmasker_gemgrijs: verbeterdfiltermetmasker_gemgrijs.c
	cc initialisatie.c groeiregio.c coocmatrix.c\
	verbeterdfiltermetmasker_gemgrijs.c -Wall -o\
	verbeterdfiltermetmasker_gemgrijs -ggdb -I/usr/X11R6/include\
	-I/usr/local/include -L/usr/X11R6/lib -L/usr/local/lib\
	-lX11 -lXext -ljpeg -lpng -ltiff  -lz -lgif -lm -lImlib
