anisofilter: anisofilter.c
	cc anisofilter.c -o anisofilter -ggdb -I/usr/X11R6/include\
-I/usr/local/include -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXext -ljpeg\
-lpng -ltiff  -lz -lgif -lm -lImlib 
