probeersel2: probeersel2.c
	cc probeersel2.c -o probeersel2 -ggdb -I/usr/X11R6/include\
-I/usr/local/include -L/usr/X11R6/lib -L/usr/local/lib -lX11 -lXext -ljpeg\
-lpng -ltiff  -lz -lgif -lm -lImlib
