#define	BLAUW	1
#define	GROEN	2
#define	GEEL	3
#define BEGINLENGTE 4
#define SLUITINGSTIJD 100
#define AANTTIKKENPERKLANT 6 //dit is 1/(kansopklant)
#define AANTLOKETTEN 4
#define VERWERKINGSTIJDGROEN 1
#define VERWERKINGSTIJDGEEL 2
#define VERWERKINGSTIJDBLAUW 3
